/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package javaapplication1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author ytb1
 */
public class bill extends javax.swing.JFrame {
   
    
    /**
     * Creates new form bill
     */
    public bill() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        corba = new javax.swing.JComboBox();
        ana_yemek = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tatlılar = new javax.swing.JComboBox();
        salatalar = new javax.swing.JLabel();
        Salatalar = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        içecekler = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        masacombo = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        corba.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mercimek", "Ezogelin", "Domates" }));
        corba.setSelectedIndex(-1);
        corba.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                corbaMouseClicked(evt);
            }
        });
        corba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                corbaActionPerformed(evt);
            }
        });

        ana_yemek.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Adana Kebab", "Urfa Kebab", "Pide", "Tas Kebab" }));
        ana_yemek.setSelectedIndex(-1);
        ana_yemek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ana_yemekActionPerformed(evt);
            }
        });

        jLabel1.setText("Corbalar");

        jLabel2.setText("Anayemek");

        jLabel3.setText("Tatlılar");

        tatlılar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ekmek Kadayıfı", "Fırında Sütlaç", "Şekerpare" }));
        tatlılar.setSelectedIndex(-1);
        tatlılar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tatlılarActionPerformed(evt);
            }
        });

        salatalar.setText("Salatalar");

        Salatalar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mevsim Salata", "Çoban Salata", "Cacık" }));
        Salatalar.setSelectedIndex(-1);
        Salatalar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalatalarActionPerformed(evt);
            }
        });

        jLabel5.setText("İçecekler");

        içecekler.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kola", "Ayran", "Meyva Suyu", "Soda" }));
        içecekler.setSelectedIndex(-1);
        içecekler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                içeceklerActionPerformed(evt);
            }
        });

        jLabel4.setText("Masa numarası : ");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Adı ", "Fiyatı"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable1);

        jButton1.setText("Odeme AL");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Kapat");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        masacombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "masa1", "masa2", "masa3" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(37, 37, 37))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(13, 13, 13)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(salatalar, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(corba, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tatlılar, 0, 100, Short.MAX_VALUE)
                        .addComponent(ana_yemek, 0, 100, Short.MAX_VALUE)
                        .addComponent(Salatalar, 0, 100, Short.MAX_VALUE)
                        .addComponent(içecekler, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(masacombo, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(corba, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(masacombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ana_yemek, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tatlılar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(salatalar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Salatalar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(içecekler, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("empty-statement")
    private void corbaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_corbaActionPerformed
   if(corba.getSelectedItem().equals("Mercimek") ){
    try{
    Class.forName("com.mysql.jdbc.Driver");
    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/proje","root","jaseen");
    Statement smt =conn.createStatement();
    DefaultTableModel tm = new DefaultTableModel();
    String sql="INSERT INTO " +masacombo.getSelectedItem()+"(yemekadı, fiyatı) VALUES ('Mercimek Corbası','5.0')"; 
    smt.executeUpdate(sql);
    conn.close();
   }
    catch(Exception hata){
        JOptionPane.showMessageDialog(rootPane, hata.toString());
            } 
    }
  
   if(corba.getSelectedItem().equals("Ezogelin") ){
    try{
    Class.forName("com.mysql.jdbc.Driver");
    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/proje","root","jaseen");
    Statement smt =conn.createStatement();
    DefaultTableModel tm = new DefaultTableModel();
    String sql="INSERT INTO " +masacombo.getSelectedItem()+"(yemekadı, fiyatı) VALUES ('Ezogelin Corbası','5.0')"; 
    smt.executeUpdate(sql);
    conn.close();
   }
    catch(Exception hata){
        JOptionPane.showMessageDialog(rootPane, hata.toString());
            } 
    }
   
   
    if (corba.getSelectedItem().equals("Domates")){
    
    try{
    Class.forName("com.mysql.jdbc.Driver");
    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/proje","root","jaseen");
    Statement smt =conn.createStatement();
    DefaultTableModel tm = new DefaultTableModel();
    String sql="INSERT INTO " +masacombo.getSelectedItem()+"(yemekadı, fiyatı) VALUES ('Domates Corbası','5.0')"; 
    smt.executeUpdate(sql);
   conn.close();
   }
   
    catch(Exception hata){
        JOptionPane.showMessageDialog(rootPane, hata.toString());
            }
    }
    try{
    Class.forName("com.mysql.jdbc.Driver");
    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/proje","root","jaseen");
    Statement smt =conn.createStatement();
    DefaultTableModel tm = new DefaultTableModel();
    String sql="SELECT * from "+masacombo.getSelectedItem();
    try(ResultSet rs = smt.executeQuery(sql)){
            int colcount = rs.getMetaData().getColumnCount();
            for(int i=1; i <= colcount; i++)
                tm.addColumn(rs.getMetaData().getColumnName(i));
            while(rs.next())
                {
                    Object[] row = new Object[colcount];
                    for(int i=1;i<=colcount;i++){
                        row[i-1] = rs.getObject(i);
                    }
                    tm.addRow(row);    
                }         
            jTable1.setModel(tm);
    }
   conn.close();
   }
    catch(Exception hata){
        JOptionPane.showMessageDialog(rootPane, hata.toString());
            } 
    // TODO add your handling code here:
    }//GEN-LAST:event_corbaActionPerformed

    private void içeceklerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_içeceklerActionPerformed
   if(içecekler.getSelectedItem().equals("Kola") ){
    try{
    Class.forName("com.mysql.jdbc.Driver");
    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/proje","root","jaseen");
    Statement smt =conn.createStatement();
    DefaultTableModel tm = new DefaultTableModel();
    String sql ="INSERT INTO " + masacombo.getSelectedItem()+"(yemekadı,fiyatı) VALUES ('Kola','3.0')";
    smt.executeUpdate(sql);
    conn.close();
   }
    catch(Exception hata){
        JOptionPane.showMessageDialog(rootPane, hata.toString());
            } 
    }
  
   if(içecekler.getSelectedItem().equals("Ayran") ){
    try{
    Class.forName("com.mysql.jdbc.Driver");
    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/proje","root","jaseen");
    Statement smt =conn.createStatement();
    DefaultTableModel tm = new DefaultTableModel();
    String sql ="INSERT INTO " + masacombo.getSelectedItem()+"(yemekadı,fiyatı) VALUES ('Ayran','2.0')";
    smt.executeUpdate(sql);
    conn.close();
   }
    catch(Exception hata){
        JOptionPane.showMessageDialog(rootPane, hata.toString());
            } 
    }
   
   if(içecekler.getSelectedItem().equals("Meyva Suyu") ){
    try{
    Class.forName("com.mysql.jdbc.Driver");
    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/proje","root","jaseen");
    Statement smt =conn.createStatement();
    DefaultTableModel tm = new DefaultTableModel();
    String sql ="INSERT INTO " + masacombo.getSelectedItem()+"(yemekadı,fiyatı) VALUES ('Meyva Suyu','3.0')";
    smt.executeUpdate(sql);
    conn.close();
   }
    catch(Exception hata){
        JOptionPane.showMessageDialog(rootPane, hata.toString());
            } 
    }
   
   if(içecekler.getSelectedItem().equals("Soda") ){
    try{
    Class.forName("com.mysql.jdbc.Driver");
    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/proje","root","jaseen");
    Statement smt =conn.createStatement();
    DefaultTableModel tm = new DefaultTableModel();
    String sql ="INSERT INTO " + masacombo.getSelectedItem()+"(yemekadı,fiyatı) VALUES ('Soda','2.0')";
    smt.executeUpdate(sql);
   conn.close();
   }
    catch(Exception hata){
        JOptionPane.showMessageDialog(rootPane, hata.toString());
            } 
    }
    try{
    Class.forName("com.mysql.jdbc.Driver");
    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/proje","root","jaseen");
    Statement smt =conn.createStatement();
    DefaultTableModel tm = new DefaultTableModel();
    TableModel model = jTable1.getModel();
    String sql="Select *from "+masacombo.getSelectedItem();
    try(ResultSet rs = smt.executeQuery(sql)){
            int colcount = rs.getMetaData().getColumnCount();
            for(int i=1; i <= colcount; i++)
                tm.addColumn(rs.getMetaData().getColumnName(i));
            while(rs.next())
                {
                    Object[] row = new Object[colcount];
                    for(int i=1;i<=colcount;i++){
                        row[i-1] = rs.getObject(i);
                    }
                    tm.addRow(row);    
                }         
            jTable1.setModel(tm);
    }
   conn.close();
   }
    catch(Exception hata){
        JOptionPane.showMessageDialog(rootPane, hata.toString());
            } 
// TODO add your handling code here:
    }//GEN-LAST:event_içeceklerActionPerformed

    private void ana_yemekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ana_yemekActionPerformed
    if(ana_yemek.getSelectedItem().equals("Adana Kebab") ){
    try{
    Class.forName("com.mysql.jdbc.Driver");
    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/proje","root","jaseen");
    Statement smt =conn.createStatement();
    DefaultTableModel tm = new DefaultTableModel();
    String sql ="INSERT INTO " + masacombo.getSelectedItem()+"(yemekadı,fiyatı) VALUES ('Adana Kebab','11.0')";
    smt.executeUpdate(sql);
   
    conn.close();
   }
    catch(Exception hata){
        JOptionPane.showMessageDialog(rootPane, hata.toString());
            } 
    }
        
    if(ana_yemek.getSelectedItem().equals("Urfa Kebab") ){
    try{
    Class.forName("com.mysql.jdbc.Driver");
    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/proje","root","jaseen");
    Statement smt =conn.createStatement();
    DefaultTableModel tm = new DefaultTableModel();
     String sql ="INSERT INTO " + masacombo.getSelectedItem()+"(yemekadı,fiyatı) VALUES ('Urfa Kebab','10.0')";
    smt.executeUpdate(sql);
   conn.close();
   }
    catch(Exception hata){
        JOptionPane.showMessageDialog(rootPane, hata.toString());
            } 
    }

    if(ana_yemek.getSelectedItem().equals("Pide") ){
    try{
    Class.forName("com.mysql.jdbc.Driver");
    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/proje","root","jaseen");
    Statement smt =conn.createStatement();
    DefaultTableModel tm = new DefaultTableModel();
    String sql ="INSERT INTO " + masacombo.getSelectedItem()+"(yemekadı,fiyatı) VALUES ('Pide','7.0')";
    smt.executeUpdate(sql);
   conn.close();
   }
    catch(Exception hata){
        JOptionPane.showMessageDialog(rootPane, hata.toString());
            } 
    }
        
    if(ana_yemek.getSelectedItem().equals("Tas Kebab") ){
    try{
    Class.forName("com.mysql.jdbc.Driver");
    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/proje","root","jaseen");
    Statement smt =conn.createStatement();
    String sql ="INSERT INTO " + masacombo.getSelectedItem()+"(yemekadı,fiyatı) VALUES ('Tas Kebab','9.0')";
    smt.executeUpdate(sql);    
   conn.close();
   }
    catch(Exception hata){
        JOptionPane.showMessageDialog(rootPane, hata.toString());
            } 
    }
    
    try{
    Class.forName("com.mysql.jdbc.Driver");
    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/proje","root","jaseen");
    Statement smt =conn.createStatement();
    DefaultTableModel tm = new DefaultTableModel();
    String sql = "SELECT * from "+masacombo.getSelectedItem();
    try(ResultSet rs = smt.executeQuery(sql)){
            int colcount = rs.getMetaData().getColumnCount();
            for(int i=1; i <= colcount; i++)
                tm.addColumn(rs.getMetaData().getColumnName(i));
            while(rs.next())
                {
                    Object[] row = new Object[colcount];
                    for(int i=1;i<=colcount;i++){
                        row[i-1] = rs.getObject(i);
                    }
                    tm.addRow(row);    
                }         
            jTable1.setModel(tm);
    }
   conn.close();
   }
    catch(Exception hata){
        JOptionPane.showMessageDialog(rootPane, hata.toString());
            } 
        // TODO add your handling code here:
    }//GEN-LAST:event_ana_yemekActionPerformed

    private void tatlılarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tatlılarActionPerformed
    if(tatlılar.getSelectedItem().equals("Ekmek Kadayıfı") ){
    try{
    Class.forName("com.mysql.jdbc.Driver");
    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/proje","root","jaseen");
    Statement smt =conn.createStatement();
    String sql ="INSERT INTO " + masacombo.getSelectedItem()+"(yemekadı,fiyatı) VALUES ('Ekmek Kadayıfı','6.0')";
    smt.executeUpdate(sql);
    //smt.executeUpdate("INSERT INTO masa1(yemekadı, fiyatı) VALUES ('Ekmek Kadayıfı','6.0') ");
   conn.close();
   }
    catch(Exception hata){
        JOptionPane.showMessageDialog(rootPane, hata.toString());
            } 
    }
    
    if(tatlılar.getSelectedItem().equals("Fırında Sütlaç") ){
    try{
    Class.forName("com.mysql.jdbc.Driver");
    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/proje","root","jaseen");
    Statement smt =conn.createStatement();
    DefaultTableModel tm = new DefaultTableModel();
    String sql ="INSERT INTO " + masacombo.getSelectedItem()+"(yemekadı,fiyatı) VALUES ('Fırında Sütlaç','6.0')";
    smt.executeUpdate(sql);
   conn.close();
   }
    catch(Exception hata){
        JOptionPane.showMessageDialog(rootPane, hata.toString());
            } 
    }
    
    if(tatlılar.getSelectedItem().equals("Şekerpare") ){
    try{
    Class.forName("com.mysql.jdbc.Driver");
    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/proje","root","jaseen");
    Statement smt =conn.createStatement();
    DefaultTableModel tm = new DefaultTableModel();
    String sql ="INSERT INTO " + masacombo.getSelectedItem()+"(yemekadı,fiyatı) VALUES ('Şekerpare','4.0')";
    smt.executeUpdate(sql);
   conn.close();
   }
    catch(Exception hata){
        JOptionPane.showMessageDialog(rootPane, hata.toString());
            } 
    }
        
    
    try{
    Class.forName("com.mysql.jdbc.Driver");
    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/proje","root","jaseen");
    Statement smt =conn.createStatement();
    DefaultTableModel tm = new DefaultTableModel();
    TableModel model = jTable1.getModel();
    String sql = "SELECT * from " +masacombo.getSelectedItem();
    try(ResultSet rs = smt.executeQuery(sql)){
            int colcount = rs.getMetaData().getColumnCount();
            for(int i=1; i <= colcount; i++)
                tm.addColumn(rs.getMetaData().getColumnName(i));
            while(rs.next())
                {
                    Object[] row = new Object[colcount];
                    for(int i=1;i<=colcount;i++){
                        row[i-1] = rs.getObject(i);
                    }
                    tm.addRow(row);    
                }         
            jTable1.setModel(tm);
    }
   conn.close();
   }
    catch(Exception hata){
        JOptionPane.showMessageDialog(rootPane, hata.toString());
            } 
    }//GEN-LAST:event_tatlılarActionPerformed

    private void SalatalarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalatalarActionPerformed
    
    if(Salatalar.getSelectedItem().equals("Mevsim Salata") ){
    try{
    Class.forName("com.mysql.jdbc.Driver");
    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/proje","root","jaseen");
    Statement smt =conn.createStatement();
    DefaultTableModel tm = new DefaultTableModel();
    String sql ="INSERT INTO " + masacombo.getSelectedItem()+"(yemekadı,fiyatı) VALUES ('Mevsim Salata','5.0')";
    smt.executeUpdate(sql);
    conn.close();
   }
    catch(Exception hata){
        JOptionPane.showMessageDialog(rootPane, hata.toString());
            } 
    } 
       
     if(Salatalar.getSelectedItem().equals("Çoban Salata") ){
    try{
    Class.forName("com.mysql.jdbc.Driver");
    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/proje","root","jaseen");
    Statement smt =conn.createStatement();
    String sql ="INSERT INTO " + masacombo.getSelectedItem()+"(yemekadı,fiyatı) VALUES ('Çoban Salata','5.0')";
    smt.executeUpdate(sql);
    conn.close();
   }
    catch(Exception hata){
        JOptionPane.showMessageDialog(rootPane, hata.toString());
            } 
    } 
        
     if(Salatalar.getSelectedItem().equals("Cacık") ){
    try{
    Class.forName("com.mysql.jdbc.Driver");
    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/proje","root","jaseen");
    Statement smt =conn.createStatement();
    DefaultTableModel tm = new DefaultTableModel();
    String sql ="INSERT INTO " + masacombo.getSelectedItem()+"(yemekadı,fiyatı) VALUES ('Cacık','3.0')";
    smt.executeUpdate(sql);
    conn.close();
   }
    catch(Exception hata){
        JOptionPane.showMessageDialog(rootPane, hata.toString());
            } 
    } 
    
    try{
    Class.forName("com.mysql.jdbc.Driver");
    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/proje","root","jaseen");
    Statement smt =conn.createStatement();
    DefaultTableModel tm = new DefaultTableModel();
    String sql = "SELECT * from " +masacombo.getSelectedItem();
    try(ResultSet rs = smt.executeQuery(sql)){
            int colcount = rs.getMetaData().getColumnCount();
            for(int i=1; i <= colcount; i++)
                tm.addColumn(rs.getMetaData().getColumnName(i));
            while(rs.next())
                {
                    Object[] row = new Object[colcount];
                    for(int i=1;i<=colcount;i++){
                        row[i-1] = rs.getObject(i);
                    }
                    tm.addRow(row);    
                }         
            jTable1.setModel(tm);
    }
   conn.close();
   }
    catch(Exception hata){
        JOptionPane.showMessageDialog(rootPane, hata.toString());
            } 
  
    }//GEN-LAST:event_SalatalarActionPerformed

    private void corbaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_corbaMouseClicked
      
// TODO add your handling code here:
    }//GEN-LAST:event_corbaMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ÖDEME().setVisible(true);
            }
        }); 
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
       

         
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Salatalar;
    private javax.swing.JComboBox ana_yemek;
    private javax.swing.JComboBox corba;
    private javax.swing.JComboBox içecekler;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox masacombo;
    private javax.swing.JLabel salatalar;
    private javax.swing.JComboBox tatlılar;
    // End of variables declaration//GEN-END:variables
}
